insta_clone/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('instagram.urls')),
   
   
]

instagram/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import upload_picture,home_page,view_post,profile,update_profile,add_comment,like_post,follow,unfollow,search_results,user_profile,signup_view
import django.contrib.auth.urls 
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views  as auth_views

app_name ="instagram"


urlpatterns=[
 
path('',home_page,name='home'),

path('accounts/', include('django.contrib.auth.urls')),
path('signup/', signup_view, name='signup'),
path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
path('logout/', auth_views.LogoutView.as_view(next_page = '/')),

path('upload/',upload_picture, name='upload'),
path('post/<int:pk>',view_post, name='view_post'),
path('profile/<str:username>',profile, name='profile'),
path('update_profile/<int:id>',update_profile, name='update_profile'),

path('add_comment/<int:post_id>',add_comment, name='add_comment'),
path('like_post/<int:post_id>',like_post, name='like_post'),

path('search/',search_results, name='search_results'),
path('user_profile/<str:username>',user_profile, name='user_profile'),



path('follow/<int:id>',follow, name='follow'),
path('unfollow/<int:id>',unfollow, name='unfollow'),


  
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

instagram/models.py
from django.db import models
from cloudinary.models import CloudinaryField  
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    profile_picture = models.ImageField(upload_to = 'pictures/',default='pictures/user.png')
    bio = models.TextField(max_length=500, default="My Bio", blank=True)
  

    def __str__(self):
        return f'{self.user.username} Profile'
    
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def save_profile(self):
        self.user

    def delete_profile(self):
        self.delete()
    
    @classmethod
    def filter_profile_by_id(cls, id):
        profile = Profile.objects.filter(user__id = id).first()
        return profile

    @classmethod
    def search_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()


class Post(models.Model):
    image = CloudinaryField('image')
    name = models.CharField(max_length=250, blank=True)
    caption = models.CharField(max_length=250, blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True, )
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ["-pk"]

    def save_post(self):
        self.save()

    def delete_post(self):
        self.delete()

    def total_likes(self):
        return self.likes.count()
    
    @classmethod
    def get_profile_posts(cls,profile):
        posts = Post.objects.filter(profile__pk= profile)
        return posts
    @classmethod
    def update_post_caption(cls,id,caption):
        update =cls.objects.filter(id=id).update(caption=caption)
        return update

    def __str__(self):
        return f'{self.user.name} Post'


class Comments(models.Model):
    comment = models.CharField(max_length=100)
    post=models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE ,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.comment} Post'
    
    def save_comment(self):
        self.save()
    
    def delete_comment(self):
        self.delete()
    
    @classmethod
    def filter_comments_by_post_id(cls, id):
        comments = Comments.objects.filter(post__id=id)
        return comments
    

    class Meta:
        ordering = ["-pk"]


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    followed = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')

    def __str__(self):
        return f'{self.follower} Follow'

instagram/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post,Profile 

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254)
    fullname=forms.CharField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'fullname', 'email', 'password1','password2')
        
        
class UploadImageModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('image','name', 'caption')

# class UpdateUserForm(forms.ModelForm):
#     email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

#     class Meta:
#         model = User
#         fields = ('username', 'email')  
        
class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'profile_picture')

instagram/views.py
from django.http.response import Http404
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.urls.base import reverse
from .forms import *
from django.contrib import messages
from .models import Post, Comments, Profile, Follow
from django.http import HttpResponseRedirect
from django.contrib.auth import logout
from django.views import generic 
from cloudinary.forms import cl_init_js_callbacks
from django.views.decorators.csrf import csrf_exempt
from .email import send_welcome_email




def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            name=form.cleaned_data['fullname']
            email=form.cleaned_data['email']
           
            send_welcome_email(name,email)

            user = authenticate(username=username, password=password)

            login(request, user)

            return redirect('instagram:home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required(login_url='/accounts/login/')
def home_page(request):
    current_user = request.user
    posts = Post.objects.all()
   
    user = User.objects.get(username=current_user.username)
    users = User.objects.exclude(username=current_user.username).exclude(is_superuser=True)
  
    
   
    ctx = {
        'posts':posts,
        'user':user,
        'users':users,
      
        }
   
    
    
    return render(request,'instagram/home_page.html',ctx)

@login_required(login_url='/accounts/login/')
def upload_picture(request):
    current_user = request.user
    user = Profile.objects.get(user=current_user)
    if request.method == 'POST':
        form = UploadImageModelForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = user
            post.save()
            return redirect('/',username=request.user)
    else:
        form = UploadImageModelForm()
    return render(request,'instagram/upload_picture.html',{'form':form})

@login_required(login_url='/accounts/login/')
def view_post(request,pk):
    post = Post.objects.get(id=pk)
    try:
        comments = Comments.filter_comments_by_post_id(pk)
        print(comments)
        
    except Comments.DoesNotExist:  
        comments = None
    
    ctx = {
        'post':post,
        "comments":comments
        }
    
    return render(request,'instagram/view_post.html',ctx)

@login_required(login_url='/accounts/login/')
def add_comment(request,post_id):
    current_user = request.user
    if request.method == 'POST':
        comment= request.POST.get('comment')
    post = Post.objects.get(id=post_id)
    user_profile = User.objects.get(username=current_user.username)
    Comments.objects.create(
         comment=comment,
         post = post,
         user=user_profile   
        )
    return redirect('instagram:view_post' ,pk=post_id)


def like_post(request,post_id):
  
    post = Post.objects.get(pk=post_id)
    is_liked=False
    user=request.user.profile
    try:
        profile=Profile.objects.get(user=user.user)
        print(profile)

    except Profile.DoesNotExist:
        raise Http404()
    if post.likes.filter(id=user.user.id).exists():
        post.likes.remove(user.user)
        is_liked=False
    else:
        post.likes.add(user.user)
        is_liked=True
    return HttpResponseRedirect(reverse('instagram:home'))


@login_required
def search_results(request):
    if 'search_profile' in request.GET and request.GET["search_profile"]:
        search_term = request.GET.get("search_profile")
        searched_profiles = Profile.search_profile(search_term)
        print(searched_profiles)
        message = f"{search_term}"
        return render(request, 'instagram/search_results.html', {"message":message,"profiles": searched_profiles})
    else:
        message = "You haven't searched for any profile"
    return render(request, 'instagram/search_results.html', {'message': message})

def follow(request,id):
    if request.method == 'GET':
        user_follow=User.objects.get(pk=id)
        follow_user=Follow(follower=request.user, followed=user_follow)
        follow_user.save()
        return redirect('instagram:user_profile' ,username=user_follow.username)
    
def unfollow(request,id):
    if request.method=='GET':
        user_unfollow=User.objects.get(pk=id)
        unfollow_user=Follow.objects.filter(follower=request.user,followed=user_unfollow)
        unfollow_user.delete()
        return redirect('instagram:user_profile' ,username=user_unfollow.username)




def profile(request,username):
    user = User.objects.get(username=username)
    posts = Post.objects.filter(user = user.id)
    follow = Follow.objects.filter(follower_id = user.id)
    
    profile=Profile.filter_profile_by_id(user.id) 

    ctx = {
        "posts":posts,
        "profile":profile,
        'user':user,
        
        }
   
    return render(request, 'profile/profile.html',ctx)

def user_profile(request,username):
    current_user = request.user
    user = User.objects.get(username=current_user.username)
    user_select = User.objects.get(username=username)
    if user_select == user:
        return redirect('instagram:profile', username=request.user.username)
    
    posts = Post.objects.filter(user = user_select.id)
    follow = Follow.objects.filter(follower_id = user_select.id)
    
    profile=Profile.filter_profile_by_id(user_select.id)
      
    followers = Follow.objects.filter(followed=user_select.id)
   
    follow_status = False
    for follower in followers:
        if user.id == follower.follower.id:
            follow_status = True
            break
        else:
            follow_status = False
  
    ctx = {
        "posts":posts,
        "profile":profile,
        "user":user,
        'user_select':user_select,
         'followers': followers,
        'follow_status': follow_status
        }
   
    return render(request, 'instagram/user_profile.html',ctx)

def update_profile(request,id):
    user = User.objects.get(id=id)
    profile = Profile.objects.get(user = user)
    form = UpdateUserProfileForm(instance=profile)
    if request.method == "POST":
            form = UpdateUserProfileForm(request.POST,request.FILES,instance=profile)
            if form.is_valid():  
                # profile.bio = form.cleaned_data['bio']
                # profile.profile_picture = form.cleaned_data['profile_picture']
                profile = form.save(commit=False)
                profile.save()
                return redirect('instagram:profile' ,username=user.username) 
            
    ctx= {"form":form}
    return render(request, 'profile/update_profile.html',ctx)
    
    
    

instagram/templates/instagram/base.html
{% load bootstrap4 %} {% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'images/favicon.ico' %}" />
    <title>Instagram</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:ital@0;1&display=swap"
      rel="stylesheet"
    />
    {% block styles %} {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% endblock %}

    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="container-fluid p-0 m-0">
      {%include "instagram/navbar.html"%} {%block content%} {%endblock content%}
    </div>
    {%include "instagram/scripts.html"%} {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %} {% endblock %}
  </body>
</html>

instagram/templates/instagram/home_page.html
{%extends 'instagram/base.html'%}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container-fluid">
  <div class="row main-container">
    <div class="col-md-7 post-container mt-3">
      {% for post in posts %}

      <div class="card m-3">
        <div class="card-header p-1">
          <div class="image">
            <img src="{{post.user.profile_picture.url}}" alt="" />
          </div>
          <div class="user_name ml-1 mb-2">{{post.user.user.username}}</div>
        </div>
        {%if post.image%}
        <a href="{%url 'instagram:view_post' post.id %}">
          <img src="{{post.image.url}}" class="card-img-top" alt="..." />
        </a>

        {%endif%}

        <div class="card-body">
          <div class="icons-container">
            <div class="like mr-3">
              <a href="{%url 'instagram:like_post' post.id %}">
                <img src="../../static/images/liked.png" alt="" />
              </a>
            </div>
            <div class="comment mr-3">
              <a href="{%url 'instagram:view_post' post.id %}">
                <img src="../../static/images/message.png" alt="" />
              </a>
            </div>
            <div class="comment">
              <a href="">
                <img src="../../static/images/share.png" alt="" />
              </a>
            </div>
          </div>
          <h5>{{post.likes.count}} likes</h5>
          <div class="card-text">
            <span class="username"> {{post.user.user.username}} </span>
            <span class="caption">{{post.caption}}</span>
          </div>
          <h5>
            <a
              class="text-decoration-none"
              href="{%url 'instagram:view_post' post.id %}"
            >
              View all comments
            </a>
          </h5>
          <span class="text-muted">{{post.created}}</span>
        </div>
        <div class="comments-form">
          <form action="{%url 'instagram:add_comment' post.id %}" method="POST">
            {%csrf_token%}
            <div class="input-group">
              <input
                type="text"
                class="form-control"
                name="comment"
                placeholder="Add comment"
              />
              <button class="btn btn-success" type="submit">Post</button>
            </div>
          </form>
        </div>
      </div>

      {% endfor %}
    </div>
    <div class="col-md-5 followers-container">
      <div class="followers-wrapper">
        <div class="user-header">
          <div class="image">
            <img src="{{user.profile.profile_picture.url}}" alt="" />
          </div>
          <div class="user_name ml-1 mb-2">{{user.username}}</div>
        </div>
        <hr class="m-0" />
        <p class="text-muted text-center mt-2 mb-2">Suggestions to follow</p>
        <div class="users-wrapper">
          {% for user in users %}

          <div class="single-user-container">
            <a
              class="text-decoration-none user"
              href="{%url 'instagram:user_profile' username=user %}"
            >
              <div class="image">
                <img src="{{user.profile.profile_picture.url}}" alt="" />
              </div>
              <div class="user_name mb-2">{{user.username}}</div>
            </a>
          </div>
          <hr />
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock%}

instagram/templates/instagram/navbar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/navbar.css" />
    <link
      rel="stylesheet"
      href="  https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    />
    <title>Instagram</title>
  </head>
  <body>
    {% load static%}
    <nav class="navbar m-0">
      <a href="/" class="navbar-brand mb-0 h1">
        <img src="../../static/images/Instagram_logo.png" alt="" />
      </a>
      <form
        class="form-inline"
        id="searchform"
        action="{% url 'instagram:search_results' %}"
        role="search"
      >
        <input
          class="form-control"
          type="search"
          placeholder="Search"
          aria-label="Search"
          id="searching"
          name="search_profile"
        />
      </form>
      {% if user.is_authenticated %}
      <ul class="icons m-0">
        <li class="nav-item">
          <a class="nav-link mr-0" href="{%url 'instagram:home'%}">
            <img src="../../static/images/home.png" alt="" class="nav-icon" />
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link mr-0" href="#">
            <img src="../../static/images/send.png" alt="" class="nav-icon" />
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link mr-0" href="{%url 'instagram:upload'%}">
            <img src="../../static/images/photo.png" alt="" class="nav-icon" />
          </a>
        </li>
        <li class="nav-item dropdown mr-5">
          <a
            class="nav-link"
            href="#"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <img
              src="{{user.profile.profile_picture.url}}"
              alt=""
              class="nav-user"
            />
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a
              class="dropdown-item"
              href="{%url 'instagram:profile' username=user %}"
              >Profile</a
            >

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/logout">Logout</a>
          </div>
        </li>
      </ul>
      {% else %}
      <li>
        <a class="btn btn-default" href="accounts/login">Login</a>
      </li>

      {%endif%}
    </nav>
    <hr class="m-0" />
  </body>
</html>

instagram/templates/instagram/scripts.html
<script>

</script>

instagram/templates/instagram/search_results.html
{%extends 'instagram/base.html'%}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container">
  <div class="users-wrapper">
    <h4 class="text-center mb-3">Search Results</h4>
    <hr />
    {% for profile in profiles %}

    <div class="single-user-container mt-3">
      <a
        class="text-decoration-none user"
        href="{%url 'instagram:user_profile' username=profile.user.username %}"
      >
        <div class="image">
          <img src="{{profile.profile_picture.url}}" alt="" />
        </div>
        <div class="user_name mb-2">{{profile.user.username.capitalize}}</div>
      </a>
    </div>
    <hr />
    {%empty%}
    <h4 class="text-center">No user found search-term {{message}}</h4>
    {% endfor %}
  </div>
</div>

{% endblock%}

instagram/templates/instagram/upload_picture.html
{%extends 'instagram/base.html'%}
<!-- bootstrap -->
{% load bootstrap4 %}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container mt-4">
  <div class="form">
    <h4 class="text-center">Upload Picture</h4>
    <form
      action="{%url 'instagram:upload' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {%csrf_token%} {% bootstrap_form form %}
      <input type="submit" class="btn btn-success btn-lg" value="Post" />
    </form>
  </div>
</div>

{% endblock%}

instagram/templates/instagram/user_profile.html
{%extends 'instagram/base.html'%}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container-fluid m-5">
  <div class="user_profile">
    <div class="image">
      {% if profile.profile_picture %}
      <img
        class="profile-picture mt-3"
        src="{{profile.profile_picture.url}}"
        alt=""
      />
      {% endif %}
    </div>
    <div class="details">
      <div class="first">
        <h3>{{user_select.username}}</h3>
        {% if follow_status %}
        <div>
          <a
            href="{%url 'instagram:unfollow' user_select.id %}"
            class="btn btn-danger"
            >Unfollow</a
          >
        </div>
        {%else%}
        <div>
          <a
            href="{%url 'instagram:follow' user_select.id %}"
            class="btn btn-success"
            >Follow</a
          >
        </div>
        {% endif %}
      </div>
      <div class="second">
        <h5>Bio</h5>
        <p class="">{{profile.bio}}</p>
      </div>
      <div class="third">
        <div class="posts ml-3"><span>{{posts.count}}</span> posts</div>
        <div class="followers ml-3">
          <span>{{user_select.followers.count}}</span> followers
        </div>
        <div class="following ml-3">
          <span>{{user_select.following.count}}</span> following
        </div>
      </div>
    </div>
  </div>
  <hr />
  <div class="user-posts">
    <div class="row">
      {% for post in posts %}
      <div class="col-md-4">
        <div class="post-wrapper">
          <a href="{%url 'instagram:view_post' post.id %}">
            <img class="img-responsive" src="{{post.image.url}}" alt="..." />
          </a>
        </div>
      </div>

      {%empty%}

      <h4 class="text-center">No posts yet</h4>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock%}

instagram/templates/instagram/view_post.html
{%extends 'instagram/base.html'%}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container">
  <div class="single_post-container row">
    <div class="col-md-6 image-container">
      <img src="{{post.image.url}}" alt="" />
    </div>
    <div class="col-md-6 comments-container">
      <div class="user">
        <div class="image">
          <img src="{{post.user.profile_picture.url}}" alt="" />
        </div>
        <div class="user_name ml-1 mb-2">{{post.user.user.username}}</div>
      </div>
      <hr />
      <div class="post">
        <span class="user_name"> {{post.user.user.username}} </span>
        {{post.name}}
        <p class="post_caption">{{post.caption}}</p>
      </div>
      <div class="comments-wrapper">
        <h4 class="text-center">Comments</h4>
        {% for comment in comments %}
        <div class="comment_wrapper">
          <div class="comment_user user_name mr-2">
            <div class="user">
              <div class="image">
                <img
                  src="{{comment.user.profile.profile_picture.url}}"
                  alt=""
                />
              </div>
              <div class="user_name ml-1 mb-2">{{comment.user.username}}</div>
            </div>
          </div>
          <div class="comment-comment mt-3">
            <p>...{{comment.comment.capitalize}}</p>
          </div>
        </div>
        <hr class="m-1 p-0" />
        {%empty%}
        <h5>No comments</h5>
        {% endfor %}
      </div>

      <div class="icons-container mt-2">
        <div class="like mr-3">
          <a href="{% url 'instagram:like_post' post_id=post.id %}">
            <img src="../../static/images/liked.png" alt="" />
          </a>
        </div>
        <div class="comment mr-3">
          <a href="#">
            <img src="../../static/images/message.png" alt="" />
          </a>
        </div>
        <div class="comment">
          <a href="">
            <img src="../../static/images/share.png" alt="" />
          </a>
        </div>
      </div>
      <h5>{{post.likes.count}} likes</h5>
      <span class="text-muted">{{post.created}}</span>
      <div class="comments-form mt-2">
        <form action="{%url 'instagram:add_comment' post.id %}" method="POST">
          {%csrf_token%}
          <div class="input-group mb-3">
            <input
              type="text"
              class="form-control"
              name="comment"
              placeholder="Add comment"
            />
            <button class="btn btn-success" type="submit">Post</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock%}